### ISSUE TITLE
Consider project dependencies

### ISSUE THREAD

**Issue by bobef** [Perennials/deploy#2]
So one sync or build would sync or build the dependencies first. Also run would sync and build first. But how to tell what is needed for a build or run? Images can are known, although with variables from files they can be variable too. Maybe something like:

``` yaml
  project:
    B:
      pod:
        deps:
          A: [ sync, build ]
```

  Also how to tell if we need to sync or not? Syncing befor each run won't be cool. But for services runs are rare occurrence so it doesn't matter if we have a flag `-no-deps` or something.
